
export const SAVE_DATA = 'SAVE_DATA';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const SAVE_DATA_FAIL = 'SAVE_DATA_FAIL'

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const SET_CATEGORY_DATA = 'SET_CATEGORY_DATA';

export const TOGGLE_VIEW_MODAL = 'TOGGLE_VIEW_MODAL'